image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
sources:
  - https://git.sr.ht/~shom/ox-hugo-nix
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  site: shom.srht.site 
tasks:
  - build: |
      mv ./ox-hugo-nix ./$site
      cd $site
      #Only build and deploy main branch
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
      complete-build; \
      fi
      nix develop --command ./build.sh --gc
  - package: |
      cd $site
      cd public
      tar -cvz . > ../site.tar.gz
  - upload: |
      cd $site
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
