baseURL = 'https://shom.srht.site/'
languageCode = 'en-us'
# title = 'Ox-Hugo CI/CD Starter Site'
theme = 'PaperMod'

# Ox-Hugo specific
[markup.goldmark.renderer]
  unsafe = true

# Theme specific
[params]
UseHugoToc = true
showtoc = true
tocopen = false
ShowReadingTime = true

[params.homeInfoParams]
Title = "Emacs + Org Mode + Ox-Hugo = ❤️"
Content = "Ox-Hugo CI/CD Starter Site. Site built from: https://git.sr.ht/~shom/ox-hugo-nix"

[[params.socialIcons]]
name = "other"
url = "https://shom.dev"

[[params.socialIcons]]
name = "mastodon"
url = "https://phanpy.social/#/fosstodon.org/a/243697"

[[params.socialIcons]]
name = "mastodon"
url = "./index.xml"
